apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello1
  template:
    metadata:
      labels:
        app: hello1
    spec:
      containers:
      - name: hello1
        image: your-dockerhub-username/hello1:{{IMAGE_TAG}}
        ports:
        - containerPort: 8080