apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello2
  template:
    metadata:
      labels:
        app: hello2
    spec:
      containers:
      - name: hello2
        image: your-dockerhub-username/hello2:{{IMAGE_TAG}}
        ports:
        - containerPort: 8082